### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by DangerousPixel** [xcodeOn1/ipa-scope#2]
Thanks for effort, i'm facing this issue even after installing requirements file.
Even I tried to install requirement manually .

```
Traceback (most recent call last):
  File "/Users/user/Downloads/ipa-scope/IPA-SCOPE.py", line 5, in <module>
    from func import logo, Helper ,unzip_ip,Fore,Style,slow1,slow,Rename_ipa
  File "/Users/user/Downloads/ipa-scope/func.py", line 48
    except FileNotFoundError:
IndentationError: unexpected indent
```

**Comment by xcodeOn1** [comment]
جرب الأن git pull تم تصليح المشكلة وشكراُ على التنبيه
